* Yet Another LFE 0.9.0 Quick Start

** Before we start
We assume user has no working Erlang system and everything Erlang related
can be uninstalled or deleted.
We assume the user has Linux, OSX or similar.
We uses sudo to install in /usr/local/bin.
We use kerl to install Erlang.
We decide on Erlang 17.3.
Except lfetool executables are installed in users $HOME directory,
or kerl installation directory.

** System cleanup
Before we try again lets remove our failed attempts.

If $ *kerl status* shows anything installed, we need to delete it.

#+BEGIN_EXAMPLE
$ kerl status
Available builds:
R16B03-1,R16B03-1
----------
Available installations:
R16B03-1 /Users/username/kerl
----------
The current active installation is:
/Users/username/kerl
#+END_EXAMPLE

: $ kerl delete installation ~/kerl
: The installation in /Users/username/kerl has been deleted

: $ kerl delete build R16B03-1
: The R16B03-1 build has been deleted


#+BEGIN_EXAMPLE
$ rm -rvf ~/.erc/
$ rm -rvf ~/.kerl/
#+END_EXAMPLE

Uninstall Erlang if it was installed using binary packages. In this example,
instead using your package system we will use kerl to install
one of the latest versions Erlang.

** Install lfetool
Please note that we use lfetool from
dev-1 branch, so that we can use latest stable LFE.

As lfetool progresses the url below will have to be updated.

#+BEGIN_EXAMPLE
$ curl -L -o ./lfetool https://raw.githubusercontent.com/lfe/lfetool/dev-v1/lfetool
$ sudo bash lfetool install
$ sudo lfetool -x
$ sudo chown $USER /usr/local/bin/lfetool
#+END_EXAMPLE

** Install other dependencies
Make sure ~/bin is in your $PATH

: $ echo $PATH

should show your ~/bin somewhere in the PATH
TODO: if somebody doesn't understand this convention then what?
Recent Windows refugee might have a problem

*** Install kerl

: $ lfetool install kerl ~/bin

*** Install Erlang

: $  lfetool install erlang 17.3 ~/erlang17.3

This installs Erlang in ~/kerl

Next we need to activate our Erlang installation.

: $ . ~/erlang17.3/activate

Now when we run:

: $ kerl status

We should see:

#+BEGIN_EXAMPLE
Available builds:
17.3,17.3
----------
Available installations:
17.3 /home/jacek/erlang17.3
----------
The current active installation is:
/home/jacek/erlang17.3
#+END_EXAMPLE

Also we can add it to our ~/.bash_profile

: $ echo ". ~/erlang17.3/activate" >> ~/.bash_profile

*** Install rebar

: $ lfetool install rebar

** Create New Project

: $  lfetool new library my-test-lib

And see expected error message.

Fix the error in:
~/my-test-lib/src/my-test-lib.lfe
so that the test can pass
replacing:

#+BEGIN_EXAMPLE
(defun my-adder (x y)
  (+ x (+ y 1)))
#+END_EXAMPLE

with:

#+BEGIN_EXAMPLE
(defun my-adder (x y)
  (+ x y))
#+END_EXAMPLE

: $ cd my-test-lib

and run the test again

: $ make check-unit

the test should pass now

* REPL

Now let's try REPL

: $ lfetool repl

You will notice that your terminal prompt '$' will change into '>'
and you should see:

#+BEGIN_EXAMPLE
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

LFE Shell V5.10.4 (abort with ^G)
>
#+END_EXAMPLE

try your first trivial Lisp code

: > (+ 1 2 3)

should give 6

** Define your own function in REPL
After the prompt > type following and press Enter:

: > (defun boo() (io:format "boo boo boo~n"))

now try typing (boo) after the prompt
and you should get boo printed 3 times in the console.

better example might be needed...

** Define a function in the source, load and execute it

Define a simple function in the source file
./src/my-test-lib.lfe

#+BEGIN_EXAMPLE
(defun my-substractor (x y)
  (- x y))
#+END_EXAMPLE

load the code in REPL

: > (c "./src/my-test-lib")

and try it

: > (my-test-lib:my-substractor 7 2)

If you get 5 then your LFE installation works.

* Hurray!

Now it's time to quit

press Ctrl-G

when you see:

: User switch command
:  -->

type *q* and press Enter

That's it.

* Further Reading
LFE documentation http://lfe.io/

* Work in Progress

/Future Plans:/

In this quick start, we will cover the following:
 * Looking at LFE code in the REPL and in modules


* Notes
<rvirding> you can take LFE directly from github and do make
<rvirding> https://github.com/rvirding/lfe
<rvirding> just cd into the lfe directory and do 'make' to compile everything
<rvirding> then do 'make install' to install lfe, lfec and lfescript (they are links into the lfe tree)
<rvirding> note that 'make install' does not copy parts of the lfe tree at all, it just links into to it so you should put it where you want it to be
<rvirding> 'make install' puts the lfe,lfec and lfescript in the same directory where it finds 'erl'
<jacek> I see
<rvirding> if you want them somewhere else then you do 'make install DESTBINDIR=/some/where/else"
<rvirding> I hope this helps
<rvirding> LFE works with both R16 and 17
<rvirding> and R15 for that matter
<jacek> so if I ran it on Ubuntu and did sudo install it would copy the executables somewhere in the /usr directory?



** more

<rvirding> 'make install' puts the lfe,lfec and lfescript in the same directory where it finds 'erl'
<jacek> I see
<rvirding> if you want them somewhere else then you do 'make install DESTBINDIR=/some/where/else"
<rvirding> I hope this helps
<rvirding> LFE works with both R16 and 17
<rvirding> and R15 for that matter
<jacek> so if I ran it on Ubuntu and did sudo install it would copy the executables somewhere in the /usr directory?
<rvirding> where it finds erl
<rvirding> on the mac it is /usr/local/bin
<rvirding> what does 'which erl' say?
<jacek> ~/erlang/bin/erl
<rvirding> then that is where make install will try to put the lfe commands
<jacek> i'm installing another build and will try it in a bit
<rvirding> if you can write there then it is no problem, otherwise you will need to use the DESTBINDIR alternative
<rvirding> btw, from where are you getting erlang? I have only used those from erlang-solutions.com
<jacek> I got Erlang 17.0 and 17.3 installed using lfetool
<jacek> i have compiled and installed lfe in expected directory
<jacek> how do i create a new lfe project that uses it?
<rvirding> the project bit is in lfetool
<rvirding> I just do lfe :-)
<rvirding> guessing here but try 'lfetool new library/service'
<rvirding> 'lfetool new service ' creates a new application with lfe, lutil and ltest in the deps
<jacek> got repl working
<rvirding> much the same as rebar
* rk[1] has quit (Read error: Connection reset by peer)
<jacek> :-)
<jacek> so i guess it is roughly the same as using lfetool
<jacek> how do i get rid of this:
<jacek> Pulling lfe from {git,"git://github.com/rvirding/lfe.git",{tag,"v0.9.0"}}
<jacek> Cloning into 'lfe'...
<jacek> Pulling lutil from {git,"https://github.com/lfex/lutil.git",{tag,"0.5.1"}}
<jacek> Cloning into 'lutil'...
<jacek> Pulling ltest from {git,"git://github.com/lfex/ltest.git",{tag,"0.4.1"}}
<jacek> Cloning into 'ltest'...
<jacek> ???
<rvirding> look in the deps directory you will see them there
<jacek> is it possible to download the source and avoind running git pull each time i start new project?
<rvirding> lfe source?
<rvirding> lfetool follows rebar here and makes a self-contained "package" with everything, you can add more if you wish
<rvirding> this is the rebar way
<jacek> i can see it, so what is the procedure for project creation with no internet connection?
<jacek> let it err and copy deps from another project?
<rvirding> yes
<jacek> ahh
<jacek> thank you
<rvirding> you lfe, lutil and ltest for the lfe bit, you add the other bits you need
