* Yet Another LFE Quick Start
** Purpose of this document
To explain why documentation has to change and suggest solution.
** Problems with Current Quick Guide
Current quick guide http://docs.lfe.io/quick-start/1.html
*** poorly designed structure.
Googling for "writing structure" shows following at the very top:
Written documents should be structured in a logical way, making them easier to
follow.

At the moment It's difficult to follow the current Quick guide.
*** out of date
Perhaps something will be done about it.
*** information in wrong place
QS section 1.1
Note that lfetool supports Erlang R15, R16, and 17.0.
should perhaps be in section 1.2
*** dilemmas
section 1.2
Perhaps we need two separate paths for kerl and pre-built packages?
Or maybe just stick to kerl?
* My Suggestion
** Before we start
We assume user has no working Erlang system and everything Erlang related
can be uninstalled or deleted.
We assume the user has Linux, OSX or similar.
And uses sudo to install in /usr/local/bin.
We use kerl to install Erlang.
We decide on Erlang R16.
** System cleanup
Before we try again lets remove our failed attempts.
remove following:

rm -rvf ~/.erc/

rm -rvf ~/.kerl/

uninstall erlang if needed
** Install lfetool
$ curl -L -o ./lfetool \

    https://raw.github.com/lfe/lfetool/stable/lfetool

$ sudo bash lfetool install

$ sudo lfetool -x

$ chown $USER /usr/local/bin/lfetool

** Install other dependencies
$  lfetool install erlang R16B03-1 ~/kerl

This install kerl in ~/kerl

Next we need to activate our Erlang installation.

$ . ~/kerl/activate

Now when we run:

$ kerl status

We should see:
Available builds:
R16B03-1,R16B03-1
----------
Available installations:
R16B03-1 /home/jacek/kerl
----------
The current active installation is:
/home/jacek/kerl

Also we can add it ot our ~/.bash_profile
$ echo ". ~/kerl/activate" >> ~/.bash_profile
